server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 39.106.140.83
    username: leyou
    password: leyou
    virtual-host: /leyou

leyou:
  sms:
    accessKeyId: LTAItNxtDfk7MJMq # 你自己的accessKeyId
    accessKeySecret: HKUID121ZM7XoubErXjUFJq84dha8W # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_143714980 #模板名称