server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql:///leyou?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.106.140.83
  rabbitmq:
    virtual-host: /leyou
    host: 39.106.140.83
    username: leyou
    password: leyou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.user.pojo
